services:
  wuzbot-engine:
    image: ghcr.io/douglassilsouza/wuzbot-engine:latest
    container_name: wuzbot-engine
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "3001:3000"
    env_file:
      - .env

    networks:
      - ContasNet

    volumes:
      - /opt/gastoapp/envs/wuzbot-engine.env:/app/.env

    deploy:
      replicas: 1

      labels:
        - traefik.enable=true
        - traefik.docker.network=ContasNet
        - traefik.http.routers.wuzbot.rule=Host(`wuzbot.dsilvamoda.cloud`)
        - traefik.http.routers.wuzbot.entrypoints=websecure
        - traefik.http.routers.wuzbot.tls=true
        - traefik.http.routers.wuzbot.tls.certresolver=letsencryptresolver
        - traefik.http.services.wuzbot.loadbalancer.server.port=3000

volumes:
  postgres_data:

networks:
  ContasNet:
    external: true
    name: ContasNet
